# Generated by Django 2.1.3 on 2019-01-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UbahPengguna',
            new_name='EditUser',
        ),
        migrations.DeleteModel(
            name='TambahPengguna',
        ),
    ]
