# Generated by Django 2.1.3 on 2019-01-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20190115_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
