# Generated by Django 2.1.3 on 2019-01-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('config_template', models.FileField(upload_to='')),
                ('config_upload_date', models.DateTimeField()),
                ('deploy_template', models.FileField(upload_to='')),
                ('deploy_upload_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadConfig',
        ),
        migrations.DeleteModel(
            name='UploadDeployment',
        ),
    ]
