# Generated by Django 2.1.3 on 2019-01-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_management', '0002_auto_20190115_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='config_upload_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='deploy_upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
