# Generated by Django 2.1.3 on 2019-01-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_management', '0004_auto_20190115_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='config_template',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='platform',
            name='deploy_template',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
