# Generated by Django 2.1.3 on 2019-01-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_management', '0005_auto_20190115_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='config_template',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='platform',
            name='deploy_template',
            field=models.FileField(upload_to=''),
        ),
    ]
