# Generated by Django 2.1.3 on 2019-01-15 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('template_management', '0006_auto_20190115_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='config_template',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='deploy_template',
        ),
        migrations.AddField(
            model_name='platform',
            name='config_template_name',
            field=models.CharField(default=datetime.datetime(2019, 1, 15, 14, 35, 11, 745970, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='config_template_url',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='deploy_template_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='deploy_template_url',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
