# Generated by Django 2.1.3 on 2019-01-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_management', '0009_auto_20190115_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='config_template_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='deploy_template_url',
            field=models.URLField(),
        ),
    ]
