# Generated by Django 2.1.3 on 2019-01-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_management', '0004_topic_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
