# Generated by Django 2.1.3 on 2019-01-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawler_name', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(max_length=100)),
                ('catch_up', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddNews',
        ),
        migrations.DeleteModel(
            name='EditNews',
        ),
    ]
