# Generated by Django 2.1.1 on 2019-01-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenName', models.CharField(max_length=100)),
                ('consumerKey', models.CharField(max_length=100)),
                ('consumerSecret', models.CharField(max_length=100)),
                ('accessKey', models.CharField(max_length=100)),
                ('accessSecret', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EditToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenName', models.CharField(max_length=100)),
                ('consumerKey', models.CharField(max_length=100)),
                ('consumerSecret', models.CharField(max_length=100)),
                ('accessKey', models.CharField(max_length=100)),
                ('accessSecret', models.CharField(max_length=100)),
            ],
        ),
    ]
