# Generated by Django 2.1.3 on 2019-01-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditToken',
            new_name='Token',
        ),
        migrations.DeleteModel(
            name='AddToken',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='accessKey',
            new_name='access_key',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='accessSecret',
            new_name='access_secret',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='consumerKey',
            new_name='consumer_key',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='consumerSecret',
            new_name='consumer_secret',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='tokenName',
            new_name='token_name',
        ),
    ]
