# Generated by Django 2.1.3 on 2019-01-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_management', '0010_auto_20190110_1641'),
        ('template_management', '0006_auto_20190115_1156'),
        ('token_management', '0003_auto_20190111_1126'),
        ('socmed_crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('config_yaml', models.CharField(max_length=100)),
                ('deploy_yaml', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='template_management.Platform')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='token_management.Token')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topic_management.Topic')),
            ],
        ),
        migrations.DeleteModel(
            name='AddSubject',
        ),
        migrations.DeleteModel(
            name='EditSubject',
        ),
    ]
