# Generated by Django 2.1.3 on 2019-01-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_crawler', '0003_auto_20190115_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='config_yaml_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='deploy_yaml_url',
            field=models.URLField(),
        ),
    ]
